// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsManager.Inferastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260911144817_DigestRecords")]
    partial class DigestRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CirclePerson", b =>
                {
                    b.Property<Guid>("CirclesCircleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CirclesCircleId", "PeoplePersonId");

                    b.HasIndex("PeoplePersonId");

                    b.ToTable("PersonCircles", (string)null);

                    b.HasData(
                        new
                        {
                            CirclesCircleId = new Guid("f0000001-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CirclesCircleId = new Guid("f0000007-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CirclesCircleId = new Guid("f0000007-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000003-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CirclesCircleId = new Guid("f0000008-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000004-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CirclesCircleId = new Guid("f0000008-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000005-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CirclesCircleId = new Guid("f0000007-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000006-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CirclesCircleId = new Guid("f000000a-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CirclesCircleId = new Guid("f0000005-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000008-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CirclesCircleId = new Guid("f0000003-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000009-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            CirclesCircleId = new Guid("f0000004-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("1000000a-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("ConnectionChannelPerson", b =>
                {
                    b.Property<Guid>("ConnectionChannelsConnectionChannelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConnectionChannelsConnectionChannelId", "PeoplePersonId");

                    b.HasIndex("PeoplePersonId");

                    b.ToTable("PersonConnectionChannels", (string)null);

                    b.HasData(
                        new
                        {
                            ConnectionChannelsConnectionChannelId = new Guid("d0000005-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ConnectionChannelsConnectionChannelId = new Guid("d0000002-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ConnectionChannelsConnectionChannelId = new Guid("d0000004-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000003-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ConnectionChannelsConnectionChannelId = new Guid("d0000008-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000004-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ConnectionChannelsConnectionChannelId = new Guid("d0000001-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000005-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ConnectionChannelsConnectionChannelId = new Guid("d0000004-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000006-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ConnectionChannelsConnectionChannelId = new Guid("d0000003-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ConnectionChannelsConnectionChannelId = new Guid("d0000006-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000008-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ConnectionChannelsConnectionChannelId = new Guid("d0000001-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000009-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ConnectionChannelsConnectionChannelId = new Guid("d0000007-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("1000000a-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.Circle", b =>
                {
                    b.Property<Guid>("CircleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CircleId");

                    b.ToTable("Circles", (string)null);

                    b.HasData(
                        new
                        {
                            CircleId = new Guid("f0000001-0000-0000-0000-000000000000"),
                            Name = "Inner Circle"
                        },
                        new
                        {
                            CircleId = new Guid("f0000002-0000-0000-0000-000000000000"),
                            Name = "Computational Social Science Lab"
                        },
                        new
                        {
                            CircleId = new Guid("f0000003-0000-0000-0000-000000000000"),
                            Name = "Capital University Alumni"
                        },
                        new
                        {
                            CircleId = new Guid("f0000004-0000-0000-0000-000000000000"),
                            Name = "Proceedit Team"
                        },
                        new
                        {
                            CircleId = new Guid("f0000005-0000-0000-0000-000000000000"),
                            Name = "Tokyo GCI Cohort"
                        },
                        new
                        {
                            CircleId = new Guid("f0000006-0000-0000-0000-000000000000"),
                            Name = "Docker & k8s Devs"
                        },
                        new
                        {
                            CircleId = new Guid("f0000007-0000-0000-0000-000000000000"),
                            Name = "Institutional Economics Book Club"
                        },
                        new
                        {
                            CircleId = new Guid("f0000008-0000-0000-0000-000000000000"),
                            Name = "UC Berkeley Audit Group"
                        },
                        new
                        {
                            CircleId = new Guid("f0000009-0000-0000-0000-000000000000"),
                            Name = "Historic Cairo Explorers"
                        },
                        new
                        {
                            CircleId = new Guid("f000000a-0000-0000-0000-000000000000"),
                            Name = "C# Mentorship"
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.ConnectionChannel", b =>
                {
                    b.Property<Guid>("ConnectionChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConnectionChannelId");

                    b.ToTable("ConnectionChannels", (string)null);

                    b.HasData(
                        new
                        {
                            ConnectionChannelId = new Guid("d0000001-0000-0000-0000-000000000000"),
                            ConnectionChannelName = "LinkedIn"
                        },
                        new
                        {
                            ConnectionChannelId = new Guid("d0000002-0000-0000-0000-000000000000"),
                            ConnectionChannelName = "Twitter (X)"
                        },
                        new
                        {
                            ConnectionChannelId = new Guid("d0000003-0000-0000-0000-000000000000"),
                            ConnectionChannelName = "GitHub"
                        },
                        new
                        {
                            ConnectionChannelId = new Guid("d0000004-0000-0000-0000-000000000000"),
                            ConnectionChannelName = "Email"
                        },
                        new
                        {
                            ConnectionChannelId = new Guid("d0000005-0000-0000-0000-000000000000"),
                            ConnectionChannelName = "WhatsApp"
                        },
                        new
                        {
                            ConnectionChannelId = new Guid("d0000006-0000-0000-0000-000000000000"),
                            ConnectionChannelName = "Discord"
                        },
                        new
                        {
                            ConnectionChannelId = new Guid("d0000007-0000-0000-0000-000000000000"),
                            ConnectionChannelName = "Slack"
                        },
                        new
                        {
                            ConnectionChannelId = new Guid("d0000008-0000-0000-0000-000000000000"),
                            ConnectionChannelName = "Zoom"
                        },
                        new
                        {
                            ConnectionChannelId = new Guid("d0000009-0000-0000-0000-000000000000"),
                            ConnectionChannelName = "Microsoft Teams"
                        },
                        new
                        {
                            ConnectionChannelId = new Guid("d000000a-0000-0000-0000-000000000000"),
                            ConnectionChannelName = "Telegram"
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.ContactItemRole", b =>
                {
                    b.Property<Guid>("ContactsRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ContactsRoleId");

                    b.HasIndex("PersonId");

                    b.ToTable("ContactItemRoles", (string)null);

                    b.HasData(
                        new
                        {
                            ContactsRoleId = new Guid("20000001-0000-0000-0000-000000000000"),
                            PersonId = new Guid("10000001-0000-0000-0000-000000000000"),
                            Role = ""
                        },
                        new
                        {
                            ContactsRoleId = new Guid("20000002-0000-0000-0000-000000000000"),
                            PersonId = new Guid("10000002-0000-0000-0000-000000000000"),
                            Role = ""
                        },
                        new
                        {
                            ContactsRoleId = new Guid("20000003-0000-0000-0000-000000000000"),
                            PersonId = new Guid("10000003-0000-0000-0000-000000000000"),
                            Role = ""
                        },
                        new
                        {
                            ContactsRoleId = new Guid("20000004-0000-0000-0000-000000000000"),
                            PersonId = new Guid("10000004-0000-0000-0000-000000000000"),
                            Role = ""
                        },
                        new
                        {
                            ContactsRoleId = new Guid("20000005-0000-0000-0000-000000000000"),
                            PersonId = new Guid("10000005-0000-0000-0000-000000000000"),
                            Role = ""
                        },
                        new
                        {
                            ContactsRoleId = new Guid("20000006-0000-0000-0000-000000000000"),
                            PersonId = new Guid("10000006-0000-0000-0000-000000000000"),
                            Role = ""
                        },
                        new
                        {
                            ContactsRoleId = new Guid("20000007-0000-0000-0000-000000000000"),
                            PersonId = new Guid("10000007-0000-0000-0000-000000000000"),
                            Role = ""
                        },
                        new
                        {
                            ContactsRoleId = new Guid("20000008-0000-0000-0000-000000000000"),
                            PersonId = new Guid("10000008-0000-0000-0000-000000000000"),
                            Role = ""
                        },
                        new
                        {
                            ContactsRoleId = new Guid("20000009-0000-0000-0000-000000000000"),
                            PersonId = new Guid("10000009-0000-0000-0000-000000000000"),
                            Role = ""
                        },
                        new
                        {
                            ContactsRoleId = new Guid("2000000a-0000-0000-0000-000000000000"),
                            PersonId = new Guid("1000000a-0000-0000-0000-000000000000"),
                            Role = ""
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InteractionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteractionTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InteractionType")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeOfInteraction")
                        .HasColumnType("datetime2");

                    b.HasKey("InteractionId");

                    b.HasIndex("PersonId");

                    b.ToTable("Interactions", (string)null);

                    b.HasData(
                        new
                        {
                            InteractionId = new Guid("a0000001-0000-0000-0000-000000000000"),
                            InteractionTitle = "Research sync on structural waste",
                            InteractionType = 0,
                            PersonId = new Guid("10000006-0000-0000-0000-000000000000"),
                            TimeOfInteraction = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InteractionId = new Guid("a0000002-0000-0000-0000-000000000000"),
                            InteractionTitle = "Code Review: C# Web API",
                            InteractionType = 0,
                            PersonId = new Guid("1000000a-0000-0000-0000-000000000000"),
                            TimeOfInteraction = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InteractionId = new Guid("a0000003-0000-0000-0000-000000000000"),
                            InteractionTitle = "Sociology debate on Durkheim",
                            InteractionType = 0,
                            PersonId = new Guid("10000004-0000-0000-0000-000000000000"),
                            TimeOfInteraction = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InteractionId = new Guid("a0000004-0000-0000-0000-000000000000"),
                            InteractionTitle = "Kubernetes cluster troubleshooting",
                            InteractionType = 0,
                            PersonId = new Guid("10000005-0000-0000-0000-000000000000"),
                            TimeOfInteraction = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InteractionId = new Guid("a0000005-0000-0000-0000-000000000000"),
                            InteractionTitle = "Cairo urban history walk planning",
                            InteractionType = 0,
                            PersonId = new Guid("10000009-0000-0000-0000-000000000000"),
                            TimeOfInteraction = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InteractionId = new Guid("a0000006-0000-0000-0000-000000000000"),
                            InteractionTitle = "GCI World Data Science kickoff",
                            InteractionType = 0,
                            PersonId = new Guid("10000008-0000-0000-0000-000000000000"),
                            TimeOfInteraction = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InteractionId = new Guid("a0000007-0000-0000-0000-000000000000"),
                            InteractionTitle = "GitHub Actions pairing session",
                            InteractionType = 0,
                            PersonId = new Guid("10000007-0000-0000-0000-000000000000"),
                            TimeOfInteraction = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InteractionId = new Guid("a0000008-0000-0000-0000-000000000000"),
                            InteractionTitle = "Catchup call across time zones",
                            InteractionType = 0,
                            PersonId = new Guid("10000001-0000-0000-0000-000000000000"),
                            TimeOfInteraction = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InteractionId = new Guid("a0000009-0000-0000-0000-000000000000"),
                            InteractionTitle = "Acemoglu reading discussion",
                            InteractionType = 0,
                            PersonId = new Guid("10000002-0000-0000-0000-000000000000"),
                            TimeOfInteraction = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InteractionId = new Guid("a000000a-0000-0000-0000-000000000000"),
                            InteractionTitle = "Institutional Economics framework mapping",
                            InteractionType = 0,
                            PersonId = new Guid("10000003-0000-0000-0000-000000000000"),
                            TimeOfInteraction = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NoteType")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NoteId");

                    b.HasIndex("PersonId");

                    b.ToTable("Notes", (string)null);

                    b.HasData(
                        new
                        {
                            NoteId = new Guid("b0000001-0000-0000-0000-000000000000"),
                            Content = "Discussed the framework of Douglass North regarding institutional constraints.",
                            NoteType = 1,
                            PersonId = new Guid("10000006-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            NoteId = new Guid("b0000002-0000-0000-0000-000000000000"),
                            Content = "Finalized the scope for the paper: 'Structural Waste within Absorptive Structures'.",
                            NoteType = 2,
                            PersonId = new Guid("10000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            NoteId = new Guid("b0000003-0000-0000-0000-000000000000"),
                            Content = "Troubleshooting the CI/CD pipeline. SonarCloud and Trivy are failing on the new C# build.",
                            NoteType = 2,
                            PersonId = new Guid("10000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            NoteId = new Guid("b0000004-0000-0000-0000-000000000000"),
                            Content = "Need to schedule a visit to Beit Yakan and tour the Abdeen architectural sites.",
                            NoteType = 3,
                            PersonId = new Guid("10000009-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            NoteId = new Guid("b0000005-0000-0000-0000-000000000000"),
                            Content = "Configured StatefulSets for the SQL Server database in Kubernetes.",
                            NoteType = 1,
                            PersonId = new Guid("10000008-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            NoteId = new Guid("b0000006-0000-0000-0000-000000000000"),
                            Content = "Drafted the thank you email to Professor Ann Swidler for her sociology lectures.",
                            NoteType = 2,
                            PersonId = new Guid("10000004-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            NoteId = new Guid("b0000007-0000-0000-0000-000000000000"),
                            Content = "Reviewing C# Repository Pattern and Serilog implementation for the Stock Management App.",
                            NoteType = 1,
                            PersonId = new Guid("1000000a-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            NoteId = new Guid("b0000008-0000-0000-0000-000000000000"),
                            Content = "Comparing cultural differences and social phenomena over a call.",
                            NoteType = 2,
                            PersonId = new Guid("10000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            NoteId = new Guid("b0000009-0000-0000-0000-000000000000"),
                            Content = "Need to catch up on the latest UC Berkeley lecture notes.",
                            NoteType = 3,
                            PersonId = new Guid("10000005-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            NoteId = new Guid("b000000a-0000-0000-0000-000000000000"),
                            Content = "Exploring the intersection of technical programming and CSS.",
                            NoteType = 1,
                            PersonId = new Guid("10000003-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.SocialMediaAccount", b =>
                {
                    b.Property<Guid>("SocialMediaAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialMediaAccountId");

                    b.ToTable("SocialMediaAccounts", (string)null);

                    b.HasData(
                        new
                        {
                            SocialMediaAccountId = new Guid("90000001-0000-0000-0000-000000000000"),
                            Platform = "LinkedIn",
                            Url = "https://linkedin.com/in/ned-ibrahim"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("90000002-0000-0000-0000-000000000000"),
                            Platform = "Twitter",
                            Url = "https://twitter.com/acemoglu"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("90000003-0000-0000-0000-000000000000"),
                            Platform = "GitHub",
                            Url = "https://github.com/munger-economics"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("90000004-0000-0000-0000-000000000000"),
                            Platform = "ResearchGate",
                            Url = "https://researchgate.net/profile/ann-swidler"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("90000005-0000-0000-0000-000000000000"),
                            Platform = "Wikipedia",
                            Url = "https://en.wikipedia.org/wiki/Emile_Durkheim"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("90000006-0000-0000-0000-000000000000"),
                            Platform = "NobelPrize",
                            Url = "https://nobelprize.org/douglass-north"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("90000007-0000-0000-0000-000000000000"),
                            Platform = "LinkedIn",
                            Url = "https://linkedin.com/in/youssef-dev"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("90000008-0000-0000-0000-000000000000"),
                            Platform = "GitHub",
                            Url = "https://github.com/kenji-gci"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("90000009-0000-0000-0000-000000000000"),
                            Platform = "Instagram",
                            Url = "https://instagram.com/sarah_cairo"
                        },
                        new
                        {
                            SocialMediaAccountId = new Guid("9000000a-0000-0000-0000-000000000000"),
                            Platform = "Twitter",
                            Url = "https://twitter.com/omar_tech"
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.SystemStatusTag", b =>
                {
                    b.Property<int>("StatusTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusTagId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusTagId");

                    b.ToTable("SystemStatusTags", (string)null);

                    b.HasData(
                        new
                        {
                            StatusTagId = 5,
                            Description = "Needs follow up",
                            Name = "Follow Up"
                        },
                        new
                        {
                            StatusTagId = 2,
                            Description = "Urgent follow up required",
                            Name = "Urgent"
                        },
                        new
                        {
                            StatusTagId = 7,
                            Description = "Spoke to them lately",
                            Name = "Recently Contacted"
                        },
                        new
                        {
                            StatusTagId = 4,
                            Description = "Owe them a response",
                            Name = "Should Reply"
                        },
                        new
                        {
                            StatusTagId = 8,
                            Description = "Awaiting their response",
                            Name = "Already Replied"
                        },
                        new
                        {
                            StatusTagId = 3,
                            Description = "They haven't replied",
                            Name = "Ignored Me"
                        },
                        new
                        {
                            StatusTagId = 10,
                            Description = "Skipped intentionally",
                            Name = "Ignored"
                        },
                        new
                        {
                            StatusTagId = 1,
                            Description = "Immediate attention needed",
                            Name = "High Priority"
                        },
                        new
                        {
                            StatusTagId = 9,
                            Description = "Get to it later",
                            Name = "Low Priority"
                        },
                        new
                        {
                            StatusTagId = 6,
                            Description = "Standard priority attention",
                            Name = "Moderate Priority"
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.UserDefinedTags", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TagId");

                    b.ToTable("UserDefinedTags");

                    b.HasData(
                        new
                        {
                            TagId = new Guid("e0000001-0000-0000-0000-000000000000"),
                            TagName = "Software Engineering"
                        },
                        new
                        {
                            TagId = new Guid("e0000002-0000-0000-0000-000000000000"),
                            TagName = "Economics Research"
                        },
                        new
                        {
                            TagId = new Guid("e0000003-0000-0000-0000-000000000000"),
                            TagName = "Capital University"
                        },
                        new
                        {
                            TagId = new Guid("e0000004-0000-0000-0000-000000000000"),
                            TagName = "Mentors"
                        },
                        new
                        {
                            TagId = new Guid("e0000005-0000-0000-0000-000000000000"),
                            TagName = "Backend Devs"
                        },
                        new
                        {
                            TagId = new Guid("e0000006-0000-0000-0000-000000000000"),
                            TagName = "Data Science"
                        },
                        new
                        {
                            TagId = new Guid("e0000007-0000-0000-0000-000000000000"),
                            TagName = "Sociology"
                        },
                        new
                        {
                            TagId = new Guid("e0000008-0000-0000-0000-000000000000"),
                            TagName = "Cairo History"
                        },
                        new
                        {
                            TagId = new Guid("e0000009-0000-0000-0000-000000000000"),
                            TagName = "Networking"
                        },
                        new
                        {
                            TagId = new Guid("e000000a-0000-0000-0000-000000000000"),
                            TagName = "Friends"
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.IdentityEntities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-SEED-CONCURRENCY-STAMP-0001",
                            Email = "testuser@contactsmanager.dev",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTUSER@CONTACTSMANAGER.DEV",
                            NormalizedUserName = "TESTUSER@CONTACTSMANAGER.DEV",
                            PasswordHash = "AQAAAAIAAYagAAAAEP9N9FETj6XBlr2nCwBktgDVpDvbmOXLKGisPywjI8prNBnxoqoHbJ5eYAlzc98QUw==",
                            PersonName = "Test User",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC-SEED-SECURITY-STAMP-0001",
                            TwoFactorEnabled = false,
                            UserName = "testuser@contactsmanager.dev"
                        });
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("c0000001-0000-0000-0000-000000000000"),
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryId = new Guid("c0000002-0000-0000-0000-000000000000"),
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryId = new Guid("c0000003-0000-0000-0000-000000000000"),
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryId = new Guid("c0000004-0000-0000-0000-000000000000"),
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryId = new Guid("c0000005-0000-0000-0000-000000000000"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = new Guid("c0000006-0000-0000-0000-000000000000"),
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            CountryId = new Guid("c0000007-0000-0000-0000-000000000000"),
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryId = new Guid("c0000008-0000-0000-0000-000000000000"),
                            CountryName = "France"
                        },
                        new
                        {
                            CountryId = new Guid("c0000009-0000-0000-0000-000000000000"),
                            CountryName = "China"
                        },
                        new
                        {
                            CountryId = new Guid("c000000a-0000-0000-0000-000000000000"),
                            CountryName = "Norway"
                        });
                });

            modelBuilder.Entity("Entities.DigestDelivery", b =>
                {
                    b.Property<Guid>("DigestDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WeekStartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("DigestDeliveryId");

                    b.HasIndex("ApplicationUserId", "WeekStartUtc")
                        .IsUnique();

                    b.ToTable("DigestDeliveries", (string)null);
                });

            modelBuilder.Entity("Entities.DigestMetric", b =>
                {
                    b.Property<Guid>("DigestMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ActionTaken")
                        .HasColumnType("bit");

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Opened")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DigestMetricId");

                    b.ToTable("DigestMetrics", (string)null);
                });

            modelBuilder.Entity("Entities.DigestPreference", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<double>("Threshold")
                        .HasColumnType("float");

                    b.HasKey("ApplicationUserId");

                    b.ToTable("DigestPreferences", (string)null);
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContextMemory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInProfile")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("NewsLetter")
                        .HasColumnType("bit");

                    b.Property<string>("Origin")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OtherInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CountryId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("10000001-0000-0000-0000-000000000000"),
                            Address = "Sydney, NSW",
                            ApplicationUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContextMemory = "Great conversations on social phenomena",
                            CountryId = new Guid("c0000002-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1998, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsDeleted = false,
                            LinkedInProfile = "linkedin.com/in/ned-ibrahim",
                            Name = "Ned Ibrahim",
                            NewsLetter = true,
                            Origin = "Met online to discuss cultural differences",
                            email = "ned@example.com",
                            phone = "+61411234567"
                        },
                        new
                        {
                            PersonId = new Guid("10000002-0000-0000-0000-000000000000"),
                            Address = "Cambridge, MA",
                            ApplicationUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContextMemory = "Author of Why Nations Fail",
                            CountryId = new Guid("c0000003-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1967, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsDeleted = false,
                            LinkedInProfile = "linkedin.com/in/dacemoglu",
                            Name = "Daron Acemoglu",
                            NewsLetter = false,
                            Origin = "Institutional Economics research",
                            email = "daron@mit.edu",
                            phone = "+12025550174"
                        },
                        new
                        {
                            PersonId = new Guid("10000003-0000-0000-0000-000000000000"),
                            Address = "Durham, NC",
                            ApplicationUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContextMemory = "Excellent pedagogical style in lectures",
                            CountryId = new Guid("c0000003-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1958, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsDeleted = false,
                            LinkedInProfile = "linkedin.com/in/mmunger",
                            Name = "Michael Munger",
                            NewsLetter = false,
                            Origin = "Academic lectures contact",
                            email = "munger@duke.edu",
                            phone = "+19195550188"
                        },
                        new
                        {
                            PersonId = new Guid("10000004-0000-0000-0000-000000000000"),
                            Address = "Berkeley, CA",
                            ApplicationUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContextMemory = "Culture in Action sociology frameworks",
                            CountryId = new Guid("c0000003-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1944, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            IsDeleted = false,
                            LinkedInProfile = "linkedin.com/in/aswidler",
                            Name = "Ann Swidler",
                            NewsLetter = true,
                            Origin = "UC Berkeley Audit",
                            email = "swidler@berkeley.edu",
                            phone = "+15105550199"
                        },
                        new
                        {
                            PersonId = new Guid("10000005-0000-0000-0000-000000000000"),
                            Address = "Paris, France",
                            ApplicationUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContextMemory = "Structural functionalism architect",
                            CountryId = new Guid("c0000008-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1858, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsDeleted = false,
                            LinkedInProfile = "",
                            Name = "Emile Durkheim",
                            NewsLetter = false,
                            Origin = "Sociology foundational reading",
                            email = "emile@sorbonne.fr",
                            phone = "+3315550123"
                        },
                        new
                        {
                            PersonId = new Guid("10000006-0000-0000-0000-000000000000"),
                            Address = "St. Louis, MO",
                            ApplicationUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContextMemory = "Nobel laureate in economics",
                            CountryId = new Guid("c0000003-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(1920, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsDeleted = false,
                            LinkedInProfile = "",
                            Name = "Douglass North",
                            NewsLetter = false,
                            Origin = "Institutional constraints research",
                            email = "north@wustl.edu",
                            phone = "+13145550145"
                        },
                        new
                        {
                            PersonId = new Guid("10000007-0000-0000-0000-000000000000"),
                            Address = "Cairo, Egypt",
                            ApplicationUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContextMemory = "Classmate in BIS academic program",
                            CountryId = new Guid("c0000001-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(2005, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsDeleted = false,
                            LinkedInProfile = "linkedin.com/in/youssef-bis",
                            Name = "Youssef",
                            NewsLetter = true,
                            Origin = "Capital University BIS",
                            email = "youssef@capital.edu.eg",
                            phone = "+201012345678"
                        },
                        new
                        {
                            PersonId = new Guid("10000008-0000-0000-0000-000000000000"),
                            Address = "Tokyo, Japan",
                            ApplicationUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContextMemory = "Data Science program partner",
                            CountryId = new Guid("c0000004-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(2002, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsDeleted = false,
                            LinkedInProfile = "linkedin.com/in/kenji-data",
                            Name = "Kenji",
                            NewsLetter = true,
                            Origin = "Tokyo GCI Cohort",
                            email = "kenji@tokyo.ac.jp",
                            phone = "+81312345678"
                        },
                        new
                        {
                            PersonId = new Guid("10000009-0000-0000-0000-000000000000"),
                            Address = "Cairo, Egypt",
                            ApplicationUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContextMemory = "Software Engineering intern colleague",
                            CountryId = new Guid("c0000001-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(2006, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            IsDeleted = false,
                            LinkedInProfile = "linkedin.com/in/sarah-dev",
                            Name = "Sarah",
                            NewsLetter = false,
                            Origin = "Proceedit Internship",
                            email = "sarah@proceedit.com",
                            phone = "+201112345678"
                        },
                        new
                        {
                            PersonId = new Guid("1000000a-0000-0000-0000-000000000000"),
                            Address = "Giza, Egypt",
                            ApplicationUserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContextMemory = "Met at Beit Yakan architectural tour",
                            CountryId = new Guid("c0000001-0000-0000-0000-000000000000"),
                            DateOfBirth = new DateTime(2001, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsDeleted = false,
                            LinkedInProfile = "linkedin.com/in/omar-arch",
                            Name = "Omar",
                            NewsLetter = true,
                            Origin = "Historic Cairo Explorers",
                            email = "omar@cairohistory.org",
                            phone = "+201212345678"
                        });
                });

            modelBuilder.Entity("Entities.RelationshipState", b =>
                {
                    b.Property<Guid>("RelationshipStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("CadenceReferenceDays")
                        .HasColumnType("float");

                    b.Property<bool>("IsBridge")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastContactAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("SilenceQuantile")
                        .HasColumnType("float");

                    b.Property<double>("TieStrength")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("UrgencyScore")
                        .HasColumnType("float");

                    b.HasKey("RelationshipStateId");

                    b.HasIndex("ApplicationUserId", "PersonId")
                        .IsUnique();

                    b.ToTable("RelationshipStates", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PersonSocialMediaAccount", b =>
                {
                    b.Property<Guid>("OtherSocialMediaAccountsSocialMediaAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OtherSocialMediaAccountsSocialMediaAccountId", "PeoplePersonId");

                    b.HasIndex("PeoplePersonId");

                    b.ToTable("PersonSocialMediaAccounts", (string)null);

                    b.HasData(
                        new
                        {
                            OtherSocialMediaAccountsSocialMediaAccountId = new Guid("90000001-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            OtherSocialMediaAccountsSocialMediaAccountId = new Guid("90000002-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            OtherSocialMediaAccountsSocialMediaAccountId = new Guid("90000003-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000003-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            OtherSocialMediaAccountsSocialMediaAccountId = new Guid("90000004-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000004-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            OtherSocialMediaAccountsSocialMediaAccountId = new Guid("90000005-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000005-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            OtherSocialMediaAccountsSocialMediaAccountId = new Guid("90000006-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000006-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            OtherSocialMediaAccountsSocialMediaAccountId = new Guid("90000007-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            OtherSocialMediaAccountsSocialMediaAccountId = new Guid("90000008-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000008-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            OtherSocialMediaAccountsSocialMediaAccountId = new Guid("90000009-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("10000009-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            OtherSocialMediaAccountsSocialMediaAccountId = new Guid("9000000a-0000-0000-0000-000000000000"),
                            PeoplePersonId = new Guid("1000000a-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("PersonSystemStatusTag", b =>
                {
                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SystemStatusTagsStatusTagId")
                        .HasColumnType("int");

                    b.HasKey("PeoplePersonId", "SystemStatusTagsStatusTagId");

                    b.HasIndex("SystemStatusTagsStatusTagId");

                    b.ToTable("PersonSystemStatusTag");

                    b.HasData(
                        new
                        {
                            PeoplePersonId = new Guid("10000001-0000-0000-0000-000000000000"),
                            SystemStatusTagsStatusTagId = 7
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000002-0000-0000-0000-000000000000"),
                            SystemStatusTagsStatusTagId = 4
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000003-0000-0000-0000-000000000000"),
                            SystemStatusTagsStatusTagId = 5
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000004-0000-0000-0000-000000000000"),
                            SystemStatusTagsStatusTagId = 1
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000005-0000-0000-0000-000000000000"),
                            SystemStatusTagsStatusTagId = 10
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000006-0000-0000-0000-000000000000"),
                            SystemStatusTagsStatusTagId = 9
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000007-0000-0000-0000-000000000000"),
                            SystemStatusTagsStatusTagId = 6
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000008-0000-0000-0000-000000000000"),
                            SystemStatusTagsStatusTagId = 2
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000009-0000-0000-0000-000000000000"),
                            SystemStatusTagsStatusTagId = 8
                        },
                        new
                        {
                            PeoplePersonId = new Guid("1000000a-0000-0000-0000-000000000000"),
                            SystemStatusTagsStatusTagId = 3
                        });
                });

            modelBuilder.Entity("PersonUserDefinedTags", b =>
                {
                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserDefinedTagsTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PeoplePersonId", "UserDefinedTagsTagId");

                    b.HasIndex("UserDefinedTagsTagId");

                    b.ToTable("PersonUserDefinedTags");

                    b.HasData(
                        new
                        {
                            PeoplePersonId = new Guid("10000001-0000-0000-0000-000000000000"),
                            UserDefinedTagsTagId = new Guid("e000000a-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000002-0000-0000-0000-000000000000"),
                            UserDefinedTagsTagId = new Guid("e0000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000003-0000-0000-0000-000000000000"),
                            UserDefinedTagsTagId = new Guid("e0000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000004-0000-0000-0000-000000000000"),
                            UserDefinedTagsTagId = new Guid("e0000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000005-0000-0000-0000-000000000000"),
                            UserDefinedTagsTagId = new Guid("e0000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000006-0000-0000-0000-000000000000"),
                            UserDefinedTagsTagId = new Guid("e0000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000007-0000-0000-0000-000000000000"),
                            UserDefinedTagsTagId = new Guid("e0000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000008-0000-0000-0000-000000000000"),
                            UserDefinedTagsTagId = new Guid("e0000006-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PeoplePersonId = new Guid("10000009-0000-0000-0000-000000000000"),
                            UserDefinedTagsTagId = new Guid("e0000003-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PeoplePersonId = new Guid("1000000a-0000-0000-0000-000000000000"),
                            UserDefinedTagsTagId = new Guid("e0000005-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("CirclePerson", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.Entities.Circle", null)
                        .WithMany()
                        .HasForeignKey("CirclesCircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConnectionChannelPerson", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.Entities.ConnectionChannel", null)
                        .WithMany()
                        .HasForeignKey("ConnectionChannelsConnectionChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.ContactItemRole", b =>
                {
                    b.HasOne("Entities.Person", "Person")
                        .WithMany("ContactItemRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("Entities.Person", "Person")
                        .WithMany("Interactions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.Note", b =>
                {
                    b.HasOne("Entities.Person", "Person")
                        .WithMany("Notes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Country", "Country")
                        .WithMany("Persons")
                        .HasForeignKey("CountryId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonSocialMediaAccount", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.Entities.SocialMediaAccount", null)
                        .WithMany()
                        .HasForeignKey("OtherSocialMediaAccountsSocialMediaAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonSystemStatusTag", b =>
                {
                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactsManger.Core.Domain.Entities.SystemStatusTag", null)
                        .WithMany()
                        .HasForeignKey("SystemStatusTagsStatusTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonUserDefinedTags", b =>
                {
                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactsManger.Core.Domain.Entities.UserDefinedTags", null)
                        .WithMany()
                        .HasForeignKey("UserDefinedTagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Navigation("ContactItemRoles");

                    b.Navigation("Interactions");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
