// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsManager.Inferastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260705085427_Update-Entities")]
    partial class UpdateEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CirclePerson", b =>
                {
                    b.Property<Guid>("CirclesCircleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CirclesCircleId", "PeoplePersonId");

                    b.HasIndex("PeoplePersonId");

                    b.ToTable("PersonCircles", (string)null);

                    b.HasData(
                        new
                        {
                            CirclesCircleId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            PeoplePersonId = new Guid("12345678-90ab-cdef-1234-567890abcdef")
                        },
                        new
                        {
                            CirclesCircleId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            PeoplePersonId = new Guid("23456789-0abc-def1-2345-67890abcdefa")
                        });
                });

            modelBuilder.Entity("ConnectionChannelPerson", b =>
                {
                    b.Property<Guid>("ConnectionChannelsConnectionChannelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConnectionChannelsConnectionChannelId", "PeoplePersonId");

                    b.HasIndex("PeoplePersonId");

                    b.ToTable("PersonConnectionChannels", (string)null);
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.Circle", b =>
                {
                    b.Property<Guid>("CircleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CircleId");

                    b.ToTable("Circles", (string)null);

                    b.HasData(
                        new
                        {
                            CircleId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Name = "Inner Circle"
                        },
                        new
                        {
                            CircleId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Name = "Professional Network"
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.ConnectionChannel", b =>
                {
                    b.Property<Guid>("ConnectionChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectionChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConnectionChannelId");

                    b.ToTable("ConnectionChannels", (string)null);
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.ContactItemRole", b =>
                {
                    b.Property<Guid>("ContactsRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ContactsRoleId");

                    b.HasIndex("PersonId");

                    b.ToTable("ContactItemRoles", (string)null);

                    b.HasData(
                        new
                        {
                            ContactsRoleId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PersonId = new Guid("12345678-90ab-cdef-1234-567890abcdef"),
                            Role = ""
                        },
                        new
                        {
                            ContactsRoleId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            PersonId = new Guid("23456789-0abc-def1-2345-67890abcdefa"),
                            Role = ""
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InteractionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteractionTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InteractionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfInteraction")
                        .HasColumnType("datetime2");

                    b.HasKey("InteractionId");

                    b.ToTable("Interactions", (string)null);

                    b.HasData(
                        new
                        {
                            InteractionId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            InteractionTitle = "Introductory Phone Call",
                            InteractionType = 0,
                            TimeOfInteraction = new DateTime(2026, 6, 15, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            InteractionId = new Guid("f2222222-2222-2222-2222-222222222222"),
                            InteractionTitle = "Strategy sync via Email",
                            InteractionType = 0,
                            TimeOfInteraction = new DateTime(2026, 7, 1, 9, 15, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NoteType")
                        .HasColumnType("int");

                    b.HasKey("NoteId");

                    b.ToTable("Notes", (string)null);

                    b.HasData(
                        new
                        {
                            NoteId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            Content = "Met at the conference. Prefers email updates.",
                            NoteType = 1
                        },
                        new
                        {
                            NoteId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            Content = "Discussed potential collaboration on the C# engine.",
                            NoteType = 3
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.SystemStatusTag", b =>
                {
                    b.Property<int>("StatusTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusTagId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusTagId");

                    b.ToTable("SystemStatusTags", (string)null);

                    b.HasData(
                        new
                        {
                            StatusTagId = 1,
                            Description = "Needs follow up",
                            Name = "Follow Up"
                        },
                        new
                        {
                            StatusTagId = 2,
                            Description = "Urgent follow up required",
                            Name = "Urgent"
                        },
                        new
                        {
                            StatusTagId = 8,
                            Description = "Immediate attention needed",
                            Name = "High Priority"
                        },
                        new
                        {
                            StatusTagId = 10,
                            Description = "Standard priority attention",
                            Name = "Moderate Priority"
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.UserDefinedTags", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TagId");

                    b.ToTable("UserDefinedTags");

                    b.HasData(
                        new
                        {
                            TagId = new Guid("e1111111-1111-1111-1111-111111111111"),
                            TagName = "Work"
                        },
                        new
                        {
                            TagId = new Guid("e2222222-2222-2222-2222-222222222222"),
                            TagName = "Friends"
                        });
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.IdentityEntities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("7c9e6645-3677-448a-95b7-511b41f17491"),
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryId = new Guid("a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = new Guid("4a91b323-6902-4d3e-b147-3a2f6990c254"),
                            CountryName = "Norway"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("NewsLetter")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("CountryId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("12345678-90ab-cdef-1234-567890abcdef"),
                            CountryId = new Guid("7c9e6645-3677-448a-95b7-511b41f17491"),
                            DateOfBirth = new DateTime(1996, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Name = "Alice",
                            NewsLetter = false,
                            phone = "1111111111"
                        },
                        new
                        {
                            PersonId = new Guid("23456789-0abc-def1-2345-67890abcdefa"),
                            CountryId = new Guid("a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6"),
                            DateOfBirth = new DateTime(2001, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Bob",
                            NewsLetter = true,
                            phone = "2222222222"
                        });
                });

            modelBuilder.Entity("InteractionPerson", b =>
                {
                    b.Property<Guid>("InteractionsInteractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InteractionsInteractionId", "PeoplePersonId");

                    b.HasIndex("PeoplePersonId");

                    b.ToTable("PersonInteractions", (string)null);

                    b.HasData(
                        new
                        {
                            InteractionsInteractionId = new Guid("f1111111-1111-1111-1111-111111111111"),
                            PeoplePersonId = new Guid("12345678-90ab-cdef-1234-567890abcdef")
                        },
                        new
                        {
                            InteractionsInteractionId = new Guid("f2222222-2222-2222-2222-222222222222"),
                            PeoplePersonId = new Guid("23456789-0abc-def1-2345-67890abcdefa")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NotePerson", b =>
                {
                    b.Property<Guid>("NotesNoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotesNoteId", "PeoplePersonId");

                    b.HasIndex("PeoplePersonId");

                    b.ToTable("PersonNotes", (string)null);

                    b.HasData(
                        new
                        {
                            NotesNoteId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            PeoplePersonId = new Guid("12345678-90ab-cdef-1234-567890abcdef")
                        },
                        new
                        {
                            NotesNoteId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            PeoplePersonId = new Guid("23456789-0abc-def1-2345-67890abcdefa")
                        });
                });

            modelBuilder.Entity("PersonSystemStatusTag", b =>
                {
                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SystemStatusTagsStatusTagId")
                        .HasColumnType("int");

                    b.HasKey("PeoplePersonId", "SystemStatusTagsStatusTagId");

                    b.HasIndex("SystemStatusTagsStatusTagId");

                    b.ToTable("PersonSystemStatusTag");

                    b.HasData(
                        new
                        {
                            PeoplePersonId = new Guid("12345678-90ab-cdef-1234-567890abcdef"),
                            SystemStatusTagsStatusTagId = 8
                        },
                        new
                        {
                            PeoplePersonId = new Guid("23456789-0abc-def1-2345-67890abcdefa"),
                            SystemStatusTagsStatusTagId = 2
                        });
                });

            modelBuilder.Entity("PersonUserDefinedTags", b =>
                {
                    b.Property<Guid>("PeoplePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserDefinedTagsTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PeoplePersonId", "UserDefinedTagsTagId");

                    b.HasIndex("UserDefinedTagsTagId");

                    b.ToTable("PersonUserDefinedTags");

                    b.HasData(
                        new
                        {
                            PeoplePersonId = new Guid("12345678-90ab-cdef-1234-567890abcdef"),
                            UserDefinedTagsTagId = new Guid("e2222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            PeoplePersonId = new Guid("23456789-0abc-def1-2345-67890abcdefa"),
                            UserDefinedTagsTagId = new Guid("e1111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("CirclePerson", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.Entities.Circle", null)
                        .WithMany()
                        .HasForeignKey("CirclesCircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConnectionChannelPerson", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.Entities.ConnectionChannel", null)
                        .WithMany()
                        .HasForeignKey("ConnectionChannelsConnectionChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContactsManger.Core.Domain.Entities.ContactItemRole", b =>
                {
                    b.HasOne("Entities.Person", "Person")
                        .WithMany("ContactItemRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.HasOne("Entities.Country", "Country")
                        .WithMany("Persons")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("InteractionPerson", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.Entities.Interaction", null)
                        .WithMany()
                        .HasForeignKey("InteractionsInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NotePerson", b =>
                {
                    b.HasOne("ContactsManger.Core.Domain.Entities.Note", null)
                        .WithMany()
                        .HasForeignKey("NotesNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonSystemStatusTag", b =>
                {
                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactsManger.Core.Domain.Entities.SystemStatusTag", null)
                        .WithMany()
                        .HasForeignKey("SystemStatusTagsStatusTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonUserDefinedTags", b =>
                {
                    b.HasOne("Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PeoplePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactsManger.Core.Domain.Entities.UserDefinedTags", null)
                        .WithMany()
                        .HasForeignKey("UserDefinedTagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Navigation("ContactItemRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
